# Configuration file for landscape.io
# See https://docs.landscape.io/configuration.html

ignore-paths:
    - build/
    - dist/
    - .env/
    - test/
    - tests/

pylint:
    disable:
        # W1202
        - logging-format-interpolation
        # C1001
        - old-style-class
