# Config file for automatic testing at travis-ci.org
language: python
python:
    - "3.3"
    - "3.4"
    - "3.5"

env:
    global:
        - LD_PRELOAD=/lib/x86_64-linux-gnu/libSegFault.so


# command to install dependencies
install:
    - pip install -U pip setuptools
    - pip install .
    - pip install -r travis_requirements.txt

# command to run tests
script:
    - py.test -l -vv --no-cov-on-fail --cov=schvalidator --cov-report=term-missing

# after_success:
#    - codecov

addons:
    code_climate:
        repo_token: 4ec76d4c5acba8dd5d02851c9b08ce0b2facd54f68ca2f97b5c3c02dfbf00913
