# Config file for automatic testing at travis-ci.org
language: python
cache: pip
python:
    - "3.4"
    - "3.5"
    - "3.6"

env:
    global:
        - LD_PRELOAD=/lib/x86_64-linux-gnu/libSegFault.so

before_install:
    - env

# command to install dependencies
install:
    - pip install -U pip setuptools
    - pip install .
    - pip install -r travis_requirements.txt

# command to run tests
script:
    - py.test -l -vv --no-cov-on-fail --cov=schvalidator --cov-report=term-missing

after_success:
    - codecov
    # - codeclimate-test-reporter
    - ./.deploy-docs.sh

addons:
    code_climate:
        repo_token: $CODECLIMATE_REPO_TOKEN

notifications:
    email:
        on_success: never
        on_failure: always

